setwd("E:/Open Data")
install.packages(c("RSocrata","tidyr","stringi","stringr","lubridate"))
library("RSocrata")
library("tidyr")
library("lubridate")
schools <- read.socrata("https://www.opendata.go.ke/resource/cy4r-ehmq.csv")
str(schools)
unique(schools$Sponsor.of.School)
CENTRAL <- c("CENTRAL GOVERNMENT/DEB","CENTRAL GOVERNMENT","CENTRAL GOVERNMET/DEB","CENTRAL  GOVERNMENT/DEB","CENTRAL GORVERNMENT/DEB","DEB")
#Changing the datatypes from factors to characters
schools$Name.of.School <- as.character(schools$Name.of.School)
schools$Level.of.Education <- as.character(schools$Level.of.Education)
schools$Status.of.School <- as.character(schools$Status.of.School)
schools$Sponsor.of.School <- as.character(schools$Sponsor.of.School)
str(schools$Sponsor.of.School)
schools$School.Institution.Type_1 <- as.character(schools$School.Institution.Type_1)
schools$School.Institution.Type_2 <- as.character(schools$School.Institution.Type_2)
schools$School.Institution.Type_3 <- as.character(schools$School.Institution.Type_3)
schools$Province <- as.character(schools$Province)
schools$County <- as.character(schools$County)
schools$Division <- as.character(schools$Division)
schools$Location <- as.character(schools$Location)
schools$Costituency <- as.character(schools$Costituency)
schools$Geolocation <- as.character(schools$Geolocation)
write.csv(schools,file="schools.csv")

unique(schools$Sponsor.of.School)
central_deb <- c("CENTRAL GOVERNMENT/DEB","CENTRAL GOVERNMET/DEB","CENTRAL GORVERNMENT/DEB",
                "CENTRAL  GOVERNMENT/DEB")
religious <- c("RELIGIOUS ORGANIZATION","RELIGIOUS ORGANISATION")
private <- c("PRIVATE INDIVIDUAL/ORGANIZATION","PRIVATE INDIVIDUAL","PRIVATE INDIVIDUAL/ORGANISATION")
local_government <- c("LOCAL GOVERNMENT AUTHORITY","LOCAL AUTHORITY","LOCAL GORVERNMENT AUTHORITY")
community <- c("COMMUNITY","NGO/CBO")

schools$Sponsor.of.School <- gsub("CENTRAL GOVERNMET/DEB","CENTRAL GOVERNMENT",schools$Sponsor.of.School)
schools$Sponsor.of.School <- gsub("CENTRAL GORVERNMENT/DEB","CENTRAL GOVERNMENT",schools$Sponsor.of.School)
schools$Sponsor.of.School <- gsub("CENTRAL  GOVERNMENT/DEB","CENTRAL GOVERNMENT",schools$Sponsor.of.School)
schools$Sponsor.of.School <- gsub("CENTRAL GOVERNMENT/DEB","CENTRAL GOVERNMENT",schools$Sponsor.of.School)
schools$Sponsor.of.School <- gsub("DEB","CENTRAL GOVERNMENT",schools$Sponsor.of.School)
unique(schools$Sponsor.of.School)

schools$Sponsor.of.School <- gsub("LOCAL GOVERNMENT AUTHORITY","LOCAL AUTHORITY",schools$Sponsor.of.School)
schools$Sponsor.of.School <- gsub("LOCAL GORVERNMENT AUTHORITY","LOCAL AUTHORITY",schools$Sponsor.of.School)
unique(schools$Sponsor.of.School)

schools$Sponsor.of.School <- gsub("RELIGIOUS ORGANIZATION","RELIGIOUS ORGANISATION",schools$Sponsor.of.School)

schools$Sponsor.of.School <- gsub("PRIVATE INDIVIDUAL/ORGANISATION","PRIVATE INDIVIDUAL",schools$Sponsor.of.School)
schools$Sponsor.of.School <- gsub("PRIVATE INDIVIDUAL/ORGANIZATION","PRIVATE INDIVIDUAL",schools$Sponsor.of.School)

schools$Sponsor.of.School <- gsub("COMMUNITY","NGO/CBO",schools$Sponsor.of.School)

